{{- if not .Values.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synthesized-tdk.fullname" . }}-secret
  labels:
  {{- include "synthesized-tdk.labels" . | nindent 4 }}
type: Opaque
data:
{{- $tplConfig  := .Values.tplConfig -}}
{{- range $k, $v := .Values.envRenderSecret }}
  {{- if $tplConfig }}
  {{ $k }}: {{ tpl $v $ | b64enc | quote }}
  {{- else }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
