apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "synthesized-tdk.fullname" . }}-cron
  labels:
    {{- include "synthesized-tdk.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronJobLimit }}
  failedJobsHistoryLimit: {{ .Values.cronJobFailedJobsLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        {{- include "synthesized-tdk.labels" . | nindent 8 }}
    spec:
      parallelism: 1 # How many pods will be instantiated at once
      completions: 1 # How many containers of the job are instantiated one after the other (sequentially) inside the pod
      backoffLimit: 3 # Maximum pod restarts in case of failure
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
          {{- include "synthesized-tdk.labels" . | nindent 12 }}
          {{- if .Values.cronJobPodLabels }}
          {{- toYaml .Values.cronJobPodLabels | nindent 12 }}
          {{- end }}
          {{- if .Values.cronJobPodAnnotations }}
          annotations:
          {{- toYaml .Values.cronJobPodAnnotations | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- if .Values.serviceAccount.enabled }}
          serviceAccountName: {{ include "synthesized-tdk.serviceAccountName" . }}
          {{- end }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}
          containers:
            - name: "tdk-cli"
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
              {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
              {{- if .Values.volumeMounts }}
              {{- toYaml .Values.volumeMounts | nindent 14 }}
              {{- end }}
              env:
              {{- range $key, $val := .Values.env }}
                - name: {{ $key }}
                  value: {{ $val | quote }}
              {{- end }}
                - name: UBBAGENT_PORT
                  value: "{{ .Values.ubbagent.port }}"
              envFrom:
                - secretRef:
                  {{- if .Values.secretRef}}
                    name: {{ .Values.secretRef }}
                  {{- else}}
                    name: {{ include "synthesized-tdk.fullname" . }}-secret
                  {{- end}}
              {{- if .Values.securityContext }}
              securityContext:
                {{- toYaml .Values.containerSecurityContext | nindent 16 }}
              {{- end }}
            {{- if .Values.ubbagent.enabled }}
            - name: "ubbagent"
              image: "{{ .Values.ubbagent.image.repository }}:{{ .Values.ubbagent.image.tag }}"
              env:
                  - name: AGENT_CONFIG_FILE
                    value: "{{ .Values.ubbagent.configDir }}/{{ .Values.ubbagent.configFile }}"
                  - name: AGENT_ENCODED_KEY
                    valueFrom:
                      secretKeyRef:
                        name: {{ .Values.reportingSecret }}
                        key: reporting-key
                  - name: AGENT_CONSUMER_ID
                    valueFrom:
                      secretKeyRef:
                        name: {{ .Values.reportingSecret }}
                        key: consumer-id
                  - name: AGENT_LOCAL_PORT
                    value: "{{ .Values.ubbagent.port }}"
              volumeMounts:
                  - name: ubbagent-config
                    mountPath: {{ .Values.ubbagent.configDir }}
              {{- end }}
          {{- if .Values.ubbagent.enabled }}
          volumes:
            - name: ubbagent-config
              configMap:
                name: {{ .Release.Name }}-ubbagent-config
          {{- end }}
          {{- if .Values.volumes }}
          {{- toYaml .Values.volumes | nindent 10 }}
          {{- end }}

          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
