{{- if .Values.ubbagent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ubbagent-config
data:
  {{ .Values.ubbagent.configFile }}: |-
{{ tpl (.Files.Get "files/ubbagent-config.yaml") . | indent 4 }}
{{- end }}